language: go
go:
  - 1.9
install:
  - go get github.com/clandry94/id3-go
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
